export { default } from "./Home.js"
export { default } from "./About.js"
export { default } from "./Dashboard.js"
export { default } from "./LogInPage.js"
export { default } from "./Profile.js"
export { default } from "./AddCase.js"
export { default } from "./LogOutPage.js"